### PR TITLE
more idiomatic code in Filters.scala

### PR DESCRIPTION
**Pull request by mberndt123**

### CODE REVIEW

**Comment by mberndt123** [comment]
Apparently the Scala 2.12.0 compiler generates public methods called "$anonfun$toJDouble$2", "$anonfun$toJDouble$2$adapted" and "$anonfun$toJDouble$1" from the toJDouble method even though it's annotated as private[this]. To me this looks like a Scala compiler bug.

One could fix the test by filtering out method names that contain $ signs.

**Comment by mberndt123** [comment]
It would be nice if somebody could comment on how to proceed with this.

**Comment by rozza** [comment]
@mberndt123 I'll take a look into it. 

This could be the reason it was written out long hand in the first place.

**Comment by lashchenko** [comment]
@rozza @mberndt123 I tried to use `private implicit class` and it looks like works as expected with Scala 2.12 and Java 8.
```scala
  private implicit class ScalaOptionDoubleToJavaDoubleOrNull(maybeDouble: Option[Double]) {
    def asJava: java.lang.Double = maybeDouble.map(double2Double).orNull
  }
  
  // ...
  
  JFilters.nearSphere(fieldName, x, y, maxDistance.asJava, minDistance.asJava)
  JFilters.nearSphere(fieldName, geometry, maxDistance.asJava, minDistance.asJava)
  JFilters.nearSphere(fieldName, geometry, maxDistance.asJava, minDistance.asJava)
  
  // ...
```
Is it make sense to use this version?

**Comment by rozza** [comment]
@lashchenko looks good

**Comment by mberndt123** [comment]
look ok to me

**Comment by rozza** [comment]
Thanks @mberndt123 for getting the ball rolling on this, the improvement was added in f3f146a.

**Pull request closed without merging**
