### PR TITLE
Add batchSize to FindObservable.

### PR DESCRIPTION
**Pull request by jCalamari**

### CODE REVIEW

**Comment by rozza** [comment]
The issue with this is the request on the Observable sets the `batchSize`, this happens in the underlying Java Driver. So setting it here on the Observable will have no impact as it will be overwritten.

Do you have any requirements for setting an alternative `batchSize` to that you are requesting?

**Comment by jCalamari** [comment]
> So setting it here on the Observable will have no impact as it will be overwritten.

I knew there would be a reason why that single method was not exposed.

> Do you have any requirements for setting an alternative batchSize to that you are requesting?

I am streaming 500k documents from mongo to Postgres and it is pretty slow. Mongo stats:

```
    *0    *0     *0     *0       1     3|0     0.0    9.4       0  859M 237M   0|0   0|0  315b  22.9k   35 rs0  PRI 2017-08-10T11:34:29Z
    *0    *0     *0     *0       1     2|0     0.0    9.4       0  859M 237M   0|0   0|0  262b  22.4k   35 rs0  PRI 2017-08-10T11:34:30Z
    *0    *0     *0     *0       1     7|0     0.0    9.4       0  859M 237M   0|0   0|0  543b  23.4k   35 rs0  PRI 2017-08-10T11:34:31Z
    *0    *0     *0     *0       1     1|0     0.0    9.4       0  859M 237M   0|0   0|0  199b  22.1k   35 rs0  PRI 2017-08-10T11:34:32Z
    *0    *0     *0     *0       1     1|0     0.0    9.4       0  859M 237M   0|0   0|0  199b  22.1k   35 rs0  PRI 2017-08-10T11:34:33Z
    *0    *0     *0     *0       1     1|0     0.0    9.4       0  859M 237M   0|0   0|0  199b  22.1k   35 rs0  PRI 2017-08-10T11:34:34Z
    *0    *0     *0     *0       1    10|0     0.0    9.4       0  859M 237M   0|0   0|0  749b  24.8k   35 rs0  PRI 2017-08-10T11:34:36Z
    *0     1     *0     *0      10    10|0     0.0    9.4       0  859M 237M   0|0   1|0 2.68k  83.3k   37 rs0  PRI 2017-08-10T11:34:37Z
    *0    *0     *0     *0      31     4|0     0.0    9.4       0  859M 237M   0|0   0|0 4.39k   177k   37 rs0  PRI 2017-08-10T11:34:38Z
insert query update delete getmore command % dirty % used flushes vsize  res qr|qw ar|aw netIn netOut conn set repl                 time
    *0    *0     *0     *0      31     3|0     0.0    9.4       0  859M 236M   0|0   0|0 4.34k   177k   37 rs0  PRI 2017-08-10T11:34:39Z
    *0    *0     *0     *0      30     3|0     0.0    9.4       0  859M 238M   0|0   0|0 4.20k   172k   37 rs0  PRI 2017-08-10T11:34:40Z
    *0    *0     *0     *0      31     2|0     0.0    9.4       0  859M 238M   0|0   0|0 4.28k   173k   37 rs0  PRI 2017-08-10T11:34:41Z
    *0    *0     *0     *0      32     5|0     0.0    9.4       0  859M 238M   0|0   0|0 4.60k   178k   37 rs0  PRI 2017-08-10T11:34:42Z
    *0    *0     *0     *0      29     1|0     0.0    9.4       0  859M 238M   0|0   0|0 3.95k   163k   37 rs0  PRI 2017-08-10T11:34:43Z
    *0    *0     *0     *0      31     1|0     0.0    9.4       0  859M 238M   0|0   0|0 4.22k   173k   37 rs0  PRI 2017-08-10T11:34:44Z
    *0    *0     *0     *0      32     1|0     0.0    9.4       0  859M 236M   0|0   0|0 4.35k   178k   37 rs0  PRI 2017-08-10T11:34:45Z
    *0    *0     *0     *0      31     8|0     0.0    9.4       0  859M 236M   0|0   0|0 4.63k   175k   37 rs0  PRI 2017-08-10T11:34:46Z
    *0    *0     *0     *0      32     3|0     0.0    9.4       0  859M 236M   0|0   0|0 4.47k   178k   37 rs0  PRI 2017-08-10T11:34:47Z
    *0    *0     *0     *0      32     3|0     0.0    9.4       0  859M 236M   0|0   0|0 4.47k   183k   37 rs0  PRI 2017-08-10T11:34:48Z
insert query update delete getmore command % dirty % used flushes vsize  res qr|qw ar|aw netIn netOut conn set repl                 time
    *0    *0     *0     *0      30     2|0     0.0    9.4       0  859M 236M   0|0   0|0 4.14k   171k   37 rs0  PRI 2017-08-10T11:34:49Z
    *0    *0     *0     *0      31     3|0     0.0    9.4       0  859M 235M   0|0   0|0 4.34k   178k   37 rs0  PRI 2017-08-10T11:34:50Z
    *0    *0     *0     *0      31     2|0     0.0    9.4       0  859M 235M   0|0   0|0 4.28k   177k   37 rs0  PRI 2017-08-10T11:34:51Z
    *0    *0     *0     *0      32     5|0     0.0    9.4       0  859M 235M   0|0   0|0 4.60k   184k   37 rs0  PRI 2017-08-10T11:34:52Z
    *0    *0     *0     *0      32     2|0     0.0    9.4       0  859M 235M   0|0   0|0 4.41k   184k   37 rs0  PRI 2017-08-10T11:34:53Z
    *0    *0     *0     *0      30     1|0     0.0    9.4       0  859M 235M   0|0   0|0 4.09k   178k   37 rs0  PRI 2017-08-10T11:34:54Z
    *0    *0     *0     *0      32     1|0     0.0    9.4       0  859M 235M   0|0   0|0 4.35k   189k   37 rs0  PRI 2017-08-10T11:34:55Z
    *0    *0     *0     *0      29     8|0     0.0    9.4       0  859M 235M   0|0   0|0 4.36k   176k   37 rs0  PRI 2017-08-10T11:34:56Z
    *0    *0     *0     *0      31     3|0     0.0    9.4       0  859M 235M   0|0   0|0 4.34k   185k   37 rs0  PRI 2017-08-10T11:34:57Z
    *0    *0     *0     *0      32     3|0     0.0    9.4       0  859M 235M   0|0   0|0 4.47k   190k   37 rs0  PRI 2017-08-10T11:34:58Z
insert query update delete getmore command % dirty % used flushes vsize  res qr|qw ar|aw netIn netOut conn set repl                 time
    *0    *0     *0     *0      30     2|0     0.0    9.4       0  859M 235M   0|0   0|0 4.14k   180k   37 rs0  PRI 2017-08-10T11:34:59Z
    *0    *0     *0     *0      30     3|0     0.0    9.4       0  859M 235M   0|0   0|0 4.20k   180k   37 rs0  PRI 2017-08-10T11:35:00Z
    *0    *0     *0     *0      33     2|0     0.0    9.4       0  859M 235M   0|0   0|0 4.55k   195k   37 rs0  PRI 2017-08-10T11:35:01Z
    *0    *0     *0     *0      32     5|0     0.0    9.4       0  859M 235M   0|0   0|0 4.60k   190k   37 rs0  PRI 2017-08-10T11:35:02Z
    *0    *0     *0     *0      31     1|0     0.0    9.4       0  859M 235M   0|0   0|0 4.22k   183k   37 rs0  PRI 2017-08-10T11:35:03Z
    *0     1     *0     *0      33     1|0     0.0    9.4       0  859M 235M   0|0   0|0 4.70k   195k   37 rs0  PRI 2017-08-10T11:35:04Z
    *0     7     *0     *0      22     2|0     0.0    9.4       0  859M 235M   0|0   0|0 4.56k   134k   37 rs0  PRI 2017-08-10T11:35:05Z
    *0     2     *0     *0       1     8|0     0.0    9.4       0  859M 235M   0|0   0|0 1.03k  25.1k   37 rs0  PRI 2017-08-10T11:35:06Z
    *0    *0     *0     *0       1     2|0     0.0    9.4       0  859M 235M   0|0   0|0  257b  22.5k   37 rs0  PRI 2017-08-10T11:35:07Z
    *0    *0     *0     *0       1     4|0     0.0    9.4       0  859M 235M   0|0   0|0  369b  22.9k   37 rs0  PRI 2017-08-10T11:35:08Z
```
It seems `getMore` batch size is set to default.

https://docs.mongodb.com/manual/reference/command/getMore/

**Comment by PiotrFras** [comment]
@rozza Shall we close? I see no reason to keep the PR pending.

**Comment by jCalamari** [comment]
@rozza Shall we close? I see no reason to keep it pending.

**Comment by rozza** [comment]
@jCalamari will close.

The batchSize is set in the [`MongoIterableSubscription`](https://github.com/mongodb/mongo-java-driver/blob/r3.4.0/driver-async/src/main/com/mongodb/async/client/MongoIterableSubscription.java#L116-L124) which is the underlying subscription for a `Observable` that come from a `MongoIterable`.

**Comment by AprilAtProtenus** [comment]
After looking at the code, it seems that the batch size is only grabbed from the underlying `FindIterable` *after* you subscribe, which is also after you would invoke `batchSize`.

If that is not the case, how *should* one set the batch size?

**Comment by AprilAtProtenus** [comment]
My team relies on `batchSize` to prevent cursors from timing out in some cases (by setting a very low batch size), and it prevents us from using the Scala driver exclusively. Is there another way to set the batch size? Or plans to add support for it? @rozza

**Pull request closed without merging**
