### PR TITLE
Build: add case class default args support

### PR DESCRIPTION
**Pull request by Panshin**
Without this functionality, it is quite difficult to use the driver. In my case, we often use this for Boolean attributes.

### CODE REVIEW

**Comment by rozza** [comment]
Thanks @Panshin!

At first glance it looks great, will review tomorrow.

**Comment by lashchenko** [comment]
@Panshin  Thank you for adding nice feature.

Method `paramLists` can returns empty list. Potentially it can be an issue with `paramLists.head`.

Maybe it makes sense to refactor the code to use:
```scala
val terms = mainType.decl(termNames.CONSTRUCTOR).asMethod.paramLists.headOption.toList.flatten.map(_.asTerm)

// or

val terms = mainType.decl(termNames.CONSTRUCTOR).asMethod.paramLists match {
  case h :: _ => h.map(_.asTerm)
  case _ => List.empty
}
```


Also `.flatMap { case (s, i) => { if (s.isParamWithDefault) { ... } else { None } } }` can be refactored as:
```scala
val params = terms.zipWithIndex.flatMap {
  case (s, i) if s.isParamWithDefault =>
    val getterName = TermName("apply$default$" + (i + 1))
    Some(q"${s.name.toString} -> ${mainType.typeSymbol.companion}.$getterName")
  case _ => None
}
```

or with `collect`:
```scala
val params = terms.zipWithIndex.collect {
  case (s, i) if s.isParamWithDefault =>
    val getterName = TermName("apply$default$" + (i + 1))
    q"${s.name.toString} -> ${mainType.typeSymbol.companion}.$getterName"
}
```

**Comment by Panshin** [comment]
@lashchenko thank you!

Look through docs:
    def paramLists: List[List[Symbol]]
"For a method with an empty parameter list, returns a list that contains the empty list (i.e. `List(List())`)."

But anyway, without head code looks more safe 👍 

And remove flatMap for collect.

**Comment by rozza** [comment]
Thanks again @Panshin - rebased and merged in e27ecd9

Also thanks to @lashchenko for your review 👍

**Comment by rozza** [comment]
Unfortunately, I've had to revert this PR, as there can be a compile time race condition and `apply$default$i` may not exist.

See [SCALA-325](https://jira.mongodb.org/browse/SCALA-325) for more information.

**Comment by Panshin** [comment]
Hello again!

According to SCALA-325, can you explain what are you expected?
Supporting of Default args is vital for my project and i could make necessary changes :)

**Pull request closed without merging**
