### PR TITLE
update mongo driver to 3.3.0

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by rozza** [comment]
Thanks @yanns, I'm currently in the process of updating the driver.  GridFS is in support is in code review and relies on 3.3.  I'm currently in the process of also adding MongoDB 3.4 features for the forthcoming release later this month.  Do you require a scala driver based off the 3.3.0 java driver or will going straight to the 3.4.0 java driver suffice?

**Comment by rozza** [comment]
No problems - there should be from now on.

I'll close this PR as master will soon update to 3.4.0-SNAPSHOT in preparation for the new features.

**Comment by yanns** [comment]
👍

**Comment by yanns** [comment]
actually we would appreciate one version with the 3.3.0 version. We would like to use the netty event loop and the 3.3.0 version fixes some bugs with it.

**Pull request closed without merging**
