### PR TITLE
Add @Key annotation support

### PR DESCRIPTION
**Pull request by Panshin**
Inspired by Salat @Key annotations.

### CODE REVIEW

**Comment by Panshin** [comment]
Can we need to discuss this?

**Comment by rozza** [comment]
@Panshin apologies for the delay, this looks good and I'll schedule for Scala 2.2. I've added [SCALA-318](https://jira.mongodb.org/browse/SCALA-318) to track it.

**Comment by Panshin** [comment]
Bump)

What about 2.2 version?

**Comment by rozza** [comment]
Thanks @Panshin, this has been merged with one amendment: Renamed to `@BsonProperty` to match the Java equivalent.

**Pull request closed without merging**
